apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  selector:
    app: my-flask-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80 # Port to access on the service
      targetPort: 5000 # Port your app is listening on inside the container
